export function mockMenuQuery() {
  let res = {
    code: 200,
    status: "Normal",
    requestId: null,
    message: "Ok",
    data: {
      data: [
        {
          id: 33,
          createBy: 1,
          createDate: "2019-11-26 10:42:01",
          humanCreateDate: "2 years ago",
          updateBy: 1,
          updateDate: "2021-04-23 14:27:39",
          humanUpdateDate: "a year ago",
          delFlag: 0,
          nameEn: "Home",
          nameZh: "主页",
          type: 1,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "home",
          pageLocation: "",
          routePath: "/home",
          routeNamespace: "/home",
          renderTarget: "_self",
          icon: "icon-zhuye",
          sort: 10,
          classify: "classifyE",
        },
        // {
        //   id: 34,
        //   createBy: 1,
        //   createDate: "2019-11-26 10:42:33",
        //   humanCreateDate: "2 years ago",
        //   updateBy: 1,
        //   updateDate: "2021-03-16 11:44:30",
        //   humanUpdateDate: "a year ago",
        //   delFlag: 0,
        //   nameEn: "Overview1",
        //   nameZh: "概览",
        //   type: 1,
        //   status: 0,
        //   level: 2,
        //   parentId: 33,
        //   permission: "home:overview",
        //   pageLocation: "/home/overview/Overview",
        //   routePath: "/home/overview",
        //   routeNamespace: "/overview",
        //   renderTarget: "_self",
        //   icon: "icon-gailan",
        //   sort: 10,
        //   classify: "classifyE",
        // },
        {
          id: 5,
          createBy: 1,
          createDate: "2019-11-01 15:54:37",
          humanCreateDate: "2 years ago",
          updateBy: -1,
          updateDate: "2020-10-26 11:08:59",
          humanUpdateDate: "a year ago",
          delFlag: 0,
          nameEn: "System Settings",
          nameZh: "系统设置",
          type: 1,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "rengine",
          pageLocation: "/rengine",
          routePath: "/rengine",
          routeNamespace: "/rengine",
          renderTarget: "_self",
          icon: "icon-xitongshezhi",
          sort: 100,
        },
        {
          id: 100,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Overview",
          nameZh: "首页",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "rengine:overview",
          pageLocation: "/rengine/overview/home/home",
          routePath: "/rengine/overview",
          routeNamespace: "/overview",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 90,
        },
        {
          id: 110,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Scenes",
          nameZh: "场景管理",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "rengine:scenes",
          pageLocation: "/rengine/scenes/scenes/scenes",
          routePath: "/rengine/scenes",
          routeNamespace: "/scenes",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 90,
        },
        {
          id: 111,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Scenes List",
          nameZh: "场景配置",
          type: 1,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:scenes:sceneses",
          pageLocation: "/rengine/scenes/scenes/scenes",
          routePath: "/rengine/scenes/sceneses",
          routeNamespace: "/sceneses",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 112,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Workflows",
          nameZh: "工作流",
          type: 1,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:workflows",
          pageLocation: "/rengine/scenes/workflows/workflows",
          routePath: "/rengine/workflows",
          routeNamespace: "/workflows",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 113,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Running History",
          nameZh: "运行历史",
          type: 3,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:workflows:runhistories",
          pageLocation: "/rengine/scenes/workflows/runhistories/runhistories",
          routePath: "/rengine/workflows/runhistories",
          routeNamespace: "/runhistories",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 114,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Rule Models",
          nameZh: "规则模型",
          type: 1,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:rules",
          pageLocation: "/rengine/scenes/rules/rules",
          routePath: "/rengine/rules",
          routeNamespace: "/rules",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 115,
          createBy: 1,
          createDate: "2022-08-15 16:17:32",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 16:17:37",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Rule Templates Edit",
          nameZh: "规则设计",
          type: 3,
          status: 0,
          level: 3,
          parentId: 113,
          permission: "rengine:design",
          pageLocation: "/rengine/scenes/rules/edit/edit",
          routePath: "/rengine/rules/edit",
          routeNamespace: "/ruletemplatesEdit",
          renderTarget: "_self",
          sort: 21,
        },
        {
          id: 116,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "User Librarys",
          nameZh: "自定义库",
          type: 1,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:userlibrarys",
          pageLocation: "/rengine/scenes/userlibrarys/userlibrarys",
          routePath: "/rengine/userlibrarys",
          routeNamespace: "/userlibrarys",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 117,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Test Datasets",
          nameZh: "测试数据集",
          type: 1,
          status: 0,
          level: 3,
          parentId: 110,
          permission: "rengine:testdatasets",
          pageLocation: "/rengine/scenes/testdatasets/testdatasets",
          routePath: "/rengine/testdatasets",
          routeNamespace: "/testdatasets",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 120,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Analysis",
          nameZh: "数据洞察",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "rengine:analysis",
          routePath: "/rengine/analysis",
          routeNamespace: "/analysis",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 100,
        },
        {
          id: 121,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Hits Statistics",
          nameZh: "命中分析",
          type: 1,
          status: 0,
          level: 3,
          parentId: 120,
          permission: "rengine:hitsstatistics",
          pageLocation: "/rengine/analysis/hitsstatistics/hitsstatistics",
          routePath: "/rengine/hitsstatistics",
          routeNamespace: "/hitsstatistics",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 130,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Settings",
          nameZh: "系统设置",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "rengine:settings",
          routePath: "/rengine/settings",
          routeNamespace: "/settings",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 100,
        },
        {
          id: 131,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Organizational management",
          nameZh: "组织管理",
          type: 1,
          status: 0,
          level: 3,
          parentId: 130,
          permission: "rengine:orgmanage",
          pageLocation: "/rengine/settings/orgmanage/orgmanage",
          routePath: "/rengine/orgmanage",
          routeNamespace: "/orgmanage",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 132,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Notifications",
          nameZh: "通知配置",
          type: 1,
          status: 0,
          level: 3,
          parentId: 130,
          permission: "rengine:notifications",
          pageLocation: "/rengine/settings/notifications/notifications",
          routePath: "/rengine/notifications",
          routeNamespace: "/notifications",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 133,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Users",
          nameZh: "用户管理",
          type: 1,
          status: 0,
          level: 3,
          parentId: 130,
          permission: "rengine:users",
          pageLocation: "/rengine/settings/users/users",
          routePath: "/rengine/users",
          routeNamespace: "/users",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 134,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Authentcation",
          nameZh: "认证集成",
          type: 1,
          status: 0,
          level: 3,
          parentId: 130,
          permission: "rengine:authentcation",
          pageLocation: "/rengine/settings/authentcation/authentcation",
          routePath: "/rengine/authentcation",
          routeNamespace: "/authentcation",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
      ],
    },
  }
  return res
}
