export function mockMenuQuery() {
  let res = {
    code: 200,
    status: "Normal",
    requestId: null,
    message: "Ok",
    data: {
      data: [
        {
          id: 33,
          createBy: 1,
          createDate: "2019-11-26 10:42:01",
          humanCreateDate: "2 years ago",
          updateBy: 1,
          updateDate: "2021-04-23 14:27:39",
          humanUpdateDate: "a year ago",
          delFlag: 0,
          nameEn: "Home",
          nameZh: "主页",
          type: 1,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "home",
          pageLocation: "",
          routePath: "/home",
          routeNamespace: "/home",
          renderTarget: "_self",
          icon: "icon-zhuye",
          sort: 10,
          classify: "classifyE",
        },
        {
          id: 34,
          createBy: 1,
          createDate: "2019-11-26 10:42:33",
          humanCreateDate: "2 years ago",
          updateBy: 1,
          updateDate: "2021-03-16 11:44:30",
          humanUpdateDate: "a year ago",
          delFlag: 0,
          nameEn: "Overview1",
          nameZh: "概览",
          type: 1,
          status: 0,
          level: 2,
          parentId: 33,
          permission: "home:overview",
          pageLocation: "/home/overview/Overview",
          routePath: "/home/overview",
          routeNamespace: "/overview",
          renderTarget: "_self",
          icon: "icon-gailan",
          sort: 10,
          classify: "classifyE",
        },

        {
          id: 163,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Scenes",
          nameZh: "场景配置",
          type: 1,
          status: 0,
          level: 3,
          parentId: 160,
          permission: "modules:GRE:scenes",
          pageLocation: "/modules/scenes/scenes",
          routePath: "/modules/scenes",
          routeNamespace: "/scenes",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 164,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "nameSpace",
          nameZh: "命名空间",
          type: 1,
          status: 0,
          level: 3,
          parentId: 160,
          permission: "modules:GRE:nameSpace",
          pageLocation: "/modules/gre/nameSpace/nameSpace",
          routePath: "/modules/GRE/nameSpace",
          routeNamespace: "/nameSpace",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 162,
          createBy: 1,
          createDate: "2022-08-15 15:29:02",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 15:29:05",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Rule Templates List",
          nameZh: "模版列表",
          type: 1,
          status: 0,
          level: 3,
          parentId: 160,
          permission: "modules:ruletemplate",
          pageLocation: "/modules/ruletemplate/ruletemplate",
          routePath: "/modules/ruletemplate",
          routeNamespace: "/ruletemplate",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 20,
        },
        {
          id: 163,
          createBy: 1,
          createDate: "2022-08-15 16:17:32",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 16:17:37",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Rule Templates Edit",
          nameZh: "规则模板编辑",
          type: 3,
          status: 0,
          level: 3,
          parentId: 162,
          permission: "modules:ruletemplate:edit",
          pageLocation: "/modules/ruletemplate/edit/edit",
          routePath: "/modules/ruletemplate/edit",
          routeNamespace: "/ruletemplatesEdit",
          renderTarget: "_self",
          sort: 21,
        },
        {
          id: 5,
          createBy: 1,
          createDate: "2019-11-01 15:54:37",
          humanCreateDate: "2 years ago",
          updateBy: -1,
          updateDate: "2020-10-26 11:08:59",
          humanUpdateDate: "a year ago",
          delFlag: 0,
          nameEn: "System Settings",
          nameZh: "系统设置",
          type: 1,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "modules",
          pageLocation: "/modules",
          routePath: "/modules",
          routeNamespace: "/modules",
          renderTarget: "_self",
          icon: "icon-xitongshezhi",
          sort: 100,
        },
        {
          id: 150,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Projects",
          nameZh: "项目管理",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "modules:projects",
          routePath: "/modules/projects",
          routeNamespace: "/project",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 90,
        },
        {
          id: 151,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Projects List",
          nameZh: "项目列表",
          type: 1,
          status: 0,
          level: 3,
          parentId: 150,
          permission: "modules:projects:projectlist",
          pageLocation: "/modules/projects/project-list/project-list",
          routePath: "/modules/projects/project-list",
          routeNamespace: "/project-list",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 152,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Workflows",
          nameZh: "工作流",
          type: 1,
          status: 0,
          level: 3,
          parentId: 150,
          permission: "modules:projects:workflow",
          pageLocation: "/modules/projects/workflow/workflow",
          routePath: "/modules/projects/workflow",
          routeNamespace: "/workflow",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 160,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Templates",
          nameZh: "规则模板",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "modules:ruletemplate",
          routePath: "/modules/ruletemplate",
          routeNamespace: "/ruletemplate",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 100,
        },
        {
          id: 180,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Librarys",
          nameZh: "类库管理",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "modules:Librarys",
          routePath: "/modules/Librarys",
          routeNamespace: "/Librarys",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 100,
        },
        {
          id: 181,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Librarys List",
          nameZh: "类库列表",
          type: 1,
          status: 0,
          level: 3,
          parentId: 180,
          permission: "modules:Librarys:library",
          pageLocation: "/modules/library/library",
          routePath: "/modules/Librarys/library",
          routeNamespace: "/hitsstatistics",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 170,
          createBy: 1,
          createDate: "2022-08-15 11:02:30",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:02:36",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Analysis",
          nameZh: "数据分析",
          type: 1,
          status: 0,
          level: 2,
          parentId: 5,
          permission: "modules:analysis",
          routePath: "/modules/analysis",
          routeNamespace: "/analysis",
          renderTarget: "_self",
          icon: "icon-monitoring",
          sort: 100,
        },
        {
          id: 171,
          createBy: 1,
          createDate: "2022-08-15 11:13:15",
          humanCreateDate: "2 days ago",
          updateBy: 1,
          updateDate: "2022-08-15 11:13:20",
          humanUpdateDate: "2 days ago",
          delFlag: 0,
          nameEn: "Hits Statistics",
          nameZh: "命中统计",
          type: 1,
          status: 0,
          level: 3,
          parentId: 170,
          permission: "modules:analysis:hitsstatistics",
          pageLocation: "/modules/analysis/hitsstatistics/hitsstatistics",
          routePath: "/modules/analysis/hitsstatistics",
          routeNamespace: "/hitsstatistics",
          renderTarget: "_self",
          icon: "icon-codeoptimizatio",
          sort: 10,
        },
        {
          id: 120,
          createBy: 1,
          createDate: "2022-04-15 10:55:04",
          humanCreateDate: "4 months ago",
          updateBy: 1,
          updateDate: "2022-04-15 10:55:07",
          humanUpdateDate: "4 months ago",
          delFlag: 0,
          nameEn: "test",
          nameZh: "test",
          type: 2,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "test",
          pageLocation: "http://10.0.0.163/#/login",
          routePath: "/test",
          routeNamespace: "/test",
          renderTarget: "_self",
          sort: 120,
        },
        {
          id: 122,
          createBy: 1,
          createDate: "2022-04-15 10:55:04",
          humanCreateDate: "4 months ago",
          updateBy: 1,
          updateDate: "2022-04-15 10:55:07",
          humanUpdateDate: "4 months ago",
          delFlag: 0,
          nameEn: "test2",
          nameZh: "test2",
          type: 2,
          status: 0,
          level: 1,
          parentId: 0,
          permission: "test",
          pageLocation: "https://httpbin.org/",
          routePath: "/test2",
          routeNamespace: "/test2",
          renderTarget: "_self",
          sort: 120,
        },
      ],
    },
  }
  return res
}
